### ISSUE TITLE
ECL Build Not Deterministic

### ISSUE THREAD

**Issue by jgarte** [g000001/lisp-critic#14]
Hi,

Have you tried to run this package with ECL?

It seems like the build is not deterministic.

![image](https://github.com/g000001/lisp-critic/assets/47760695/c9c2e2bf-df60-42d0-bd21-b4c8fe757eef)

https://matrix.to/#/!ztZtEudHNaAtPxrGgy:matrix.org/$b56Q1udaCntVnwGpoQu4RQKL9MDiCe4SSW7_UMXzcJA?via=libera.chat&via=matrix.org&via=mozilla.org

**Comment by g000001** [comment]
Hi,
I have been checking to build on ECL 21.2.1 again. It seem to fine.
Other report (slightly old)
https://cl-test-grid.common-lisp.dev/library/lisp-critic.html
And also your lisp-critic build process has been sucseeded in your report.
(in "phase `check` suceeded" section)

It seems to me your reporting error is GUIX system specific.
It is nice to asking GUIX packager.
https://packages.guix.gnu.org/packages/ecl-lisp-critic/1.1-1.ea19f82/

P.S. lisp-critic is a style-checker for interactive use mainly. Not a linter for static use. Although GUIX explains lisp-critic is `Common Lisp linter`...

Thank you.

**Comment by jgarte** [comment]
> P.S. lisp-critic is a style-checker for interactive use mainly. Not a linter for static use. Although GUIX explains lisp-critic is 

Thanks for the reply. I'll update that in the Guix package.

> It seems to me your reporting error is GUIX system specific.

Yes, I think it might be. I don't fully understand it yet.
