### ISSUE TITLE
Check-prefix rule should not consider issue usage of standard functions like CHECK-TYPE

### ISSUE THREAD

**Issue by svetlyak40wt** [g000001/lisp-critic#15]
A new rule check-prefix was added [6 months ago](https://github.com/g000001/lisp-critic/blame/ea19f82a168a6119ac1b10d0f457c01a7119602f/lisp-rules.lisp#L803). However now it produces too many warnings on all my projects where `check-type` function is used to ensure contact on input values:

```lisp
(DEFUN %RENDER-ERROR-PLACEHOLDER
       (NAME WIDGET-CLASS ERROR-PLACEHOLDERS)
  (CHECK-TYPE NAME STRING)
  (LET ((WIDGET (MAKE-INSTANCE WIDGET-CLASS :NAME NAME)))
    (SETF (GETHASH NAME ERROR-PLACEHOLDERS) WIDGET)
    (REBLOCKS/WIDGET:RENDER WIDGET)
    (VALUES)))
----------------------------------------------------------------------
[check-prefix]: check is not a helpful prefix. It doesn't say what
happens after checking. If this is a predicate, use a property-p name
to say what it tests for.
```

I think the rule should not warn about standard functions usage. Probably it should match only `(defun check-some-thing ...)` forms only?

**Comment by g000001** [comment]
Sorry for the late reply. 
`check-prefix` now checks user defined name (non CL packge symbols) only.
https://github.com/g000001/lisp-critic/commit/42b7dec136b12010aa811f414eba12b1dadc35a7

Thank you.

**Comment by svetlyak40wt** [comment]
Thank you!
