### ISSUE TITLE
progn-single-form ignore unquote-splicing?

### ISSUE THREAD

**Issue by kilianmh** [g000001/lisp-critic#16]
There is a legit use for `progn-single-form` which appears quite often with `unquote-splicing` (or `eclector.reader:unqote-splicing`). Maybe its more appropriate to not give the critic in this case?

**Comment by g000001** [comment]
I think PROGN-SINGLE-FORM was added for human programmer(especially newbe) mainly.

(and I have no idea to distinct proper meaningless PROGN-SINGLE-FORM context and auto generated PROGN context without big modifying with existing codes or libraries.)

It might be a easiyest solution for seasoned programmer is just do


```cl
(lisp-critic:remove-lisp-pattern 'lisp-critic::progn-single-form)
```

Thank you.
