### ISSUE TITLE
(= num (length ...))

### ISSUE THREAD

**Issue by defaultxr** [g000001/lisp-critic#3]
lisp-critic makes this critique:

```
If VAR is a list, not a vector, don't use = and LENGTH. LENGTH has
to CDR down the entire list. Use (NULL (CDR ...)) with the
appropriate number of CDR's. That will run in constant time,
independent of list length.
```

Avoiding `length` for lists is a good idea, but the suggestion of using `(null (cdr ...))` instead doesn't seem like a good alternative; for example:

```lisp
(= 2 (length (list 1))) ;; returns NIL

(null (cdr (cdr (list 1)))) ;; returns T (wrong!)
```

It might be better to suggest using `alexandria:length=` instead:

```lisp
(alexandria:length= 2 (list 1)) ;; returns NIL
(alexandria:length= 2 (list 1 2)) ;; returns T
```

According to its docstring, it has a special case that generates more efficient code when its first argument is an integer.

**Comment by g000001** [comment]
Hi,

Your suggest is nice catch, I think.
Since I'm not the author, and the author seems to have the own repositories recently.
How about telling your suggestion to the author directly? 
https://gitlab.com/criesbeck/cs325/blob/master/lisp-rules.lisp#L580

:+1:

**Comment by g000001** [comment]
My repo's `length=num` rule has been fixed. https://github.com/g000001/lisp-critic/pull/5/commits/04aa305afbdac75a266bd29c51c2ae631c2dbe01
Thank you for your suggesting.
