### ISSUE TITLE
Is this repository a fork?

### ISSUE THREAD

**Issue by ghost** [g000001/lisp-critic#8]
Hi. I have a question. What is the difference between this repository and https://gitlab.com/criesbeck/cs325?

Is this a fork to improve upon the linked project, or is it a fork to be integrated with Quicklisp. or simply a mirror?

Thanks.

**Comment by g000001** [comment]
Hi.

This fork is for integrated with Quicklisp.
Times ago, I packaged ASDF system for my own use.
Someone picked up this and registing to quicklisp...
So I maintain for lisp-critiq/quicklisp 
When official release will be comming to Quicklisp, I will be closing this repo.

Thanks.
